services:
  - type: web
    name: catchbutter
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22